github: ["atul‑labs", "open‑source‑friend"]
patreon: "atulpatreon"
open_collective: "trust‑lens"
ko_fi: "atulcoffee"
tidelift: "npm/trust‑lens"
liberapay: "atul"
buy_me_a_coffee: "https://buymeacoffee.com/atul_dev"
custom: ["https://buymeacoffee.com/atul_dev"]

